DROP TABLE instructors;
DROP TABLE lift_operators;
DROP TABLE skiers;
DROP TABLE lessons;
DROP TABLE chair_lifts;
DROP TABLE weather;

CREATE TABLE instructors
(
    ID VARCHAR2(15) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL
);

CREATE TABLE lift_operators
(
    ID VARCHAR(15) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    HOURS_PER_WEEK float(3,3) NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL
);

CREATE TABLE skier 
(
    PHONE_NUMBER(10) PRIMARY KEY,
    EXPERIENCE_LEVEL VARCHAR(20) NOT NULL,
    NAME VARCHAR(50) NOT NULL
);

CREATE TABLE lessons
(
   DATE_OF_LESSON date,
   DIFFICULTY_LEVEL VARCHAR(20),
   LOCATION VARCHAR(30),
   NUMBER_OF_STUDENTS INT(100)
);

CREATE TABLE chair_lifts
(
    START_POINT varchar(30) PRIMARY KEY,
    END_POINT varchar(30),
    IS_RUNNING INT(2)
);

CREATE TABLE weather 
(
  WHEN DATE,
  FORCAST VARCHAR(20)
);


COMMIT;

